
def get_dataset_specified_config(dataset):
    """Get dataset specific."""
    cfg = {
       "ImageNet": {
            "TRAINER.KDPT_MAPLE_2.PROMPT_DEPTH": 3,
            "TRAINER.KDPT_MAPLE_2.N_CTX": 2,
            "TRAINER.W": 4.0,
            "TRAINER.W1": 2.0,
            "TRAINER.W2": 4.0,
            "OPTIM.MAX_EPOCH": 2,
            "OPTIM.LR": 0.0026,
        },
        "ImageNetSketch": {
            "TRAINER.KDPT_MAPLE_2.PROMPT_DEPTH": 3,
            "TRAINER.KDPT_MAPLE_2.N_CTX": 2,
            "TRAINER.W": 4.0,
            "TRAINER.W1": 2.0,
            "TRAINER.W2": 4.0,
            "OPTIM.MAX_EPOCH": 2,
            "OPTIM.LR": 0.0026,
        },
        "ImageNetV2": {
            "TRAINER.KDPT_MAPLE_2.PROMPT_DEPTH": 3,
            "TRAINER.KDPT_MAPLE_2.N_CTX": 2,
            "TRAINER.W": 4.0,
            "TRAINER.W1": 2.0,
            "TRAINER.W2": 4.0,
            "OPTIM.MAX_EPOCH": 2,
            "OPTIM.LR": 0.0026,
        },
        "ImageNetA": {
            "TRAINER.KDPT_MAPLE_2.PROMPT_DEPTH": 3,
            "TRAINER.KDPT_MAPLE_2.N_CTX": 2,
            "TRAINER.W": 4.0,
            "TRAINER.W1": 2.0,
            "TRAINER.W2": 4.0,
            "OPTIM.MAX_EPOCH": 2,
            "OPTIM.LR": 0.0026,
        },
        "ImageNetR": {
            "TRAINER.KDPT_MAPLE_2.PROMPT_DEPTH": 3,
            "TRAINER.KDPT_MAPLE_2.N_CTX": 2,
            "TRAINER.W": 4.0,
            "TRAINER.W1": 2.0,
            "TRAINER.W2": 4.0,
            "OPTIM.MAX_EPOCH": 2,
            "OPTIM.LR": 0.0026,
        },
        "Caltech101": {
            "TRAINER.KDPT_MAPLE_2.PROMPT_DEPTH": 3,
            "TRAINER.KDPT_MAPLE_2.N_CTX": 2,
            "TRAINER.W": 4.0,
            "TRAINER.W1": 2.0,
            "TRAINER.W2": 4.0,
            "OPTIM.MAX_EPOCH": 2,
            "OPTIM.LR": 0.0026,
        },
        "OxfordPets": {
            "TRAINER.KDPT_MAPLE_2.PROMPT_DEPTH": 3,
            "TRAINER.KDPT_MAPLE_2.N_CTX": 2,
            "TRAINER.W": 4.0,
            "TRAINER.W1": 2.0,
            "TRAINER.W2": 4.0,
            "OPTIM.MAX_EPOCH": 2,
            "OPTIM.LR": 0.0026,
        },
        "StanfordCars": {
            "TRAINER.KDPT_MAPLE_2.PROMPT_DEPTH": 3,
            "TRAINER.KDPT_MAPLE_2.N_CTX": 2,
            "TRAINER.W": 4.0,
            "TRAINER.W1": 2.0,
            "TRAINER.W2": 4.0,
            "OPTIM.MAX_EPOCH": 2,
            "OPTIM.LR": 0.0026,
        },
        "OxfordFlowers": {
            "TRAINER.KDPT_MAPLE_2.PROMPT_DEPTH": 3,
            "TRAINER.KDPT_MAPLE_2.N_CTX": 2,
            "TRAINER.W": 4.0,
            "TRAINER.W1": 2.0,
            "TRAINER.W2": 4.0,
            "OPTIM.MAX_EPOCH": 2,
            "OPTIM.LR": 0.0026,
        },
        "Food101": {
            "TRAINER.KDPT_MAPLE_2.PROMPT_DEPTH": 3,
            "TRAINER.KDPT_MAPLE_2.N_CTX": 2,
            "TRAINER.W": 4.0,
            "TRAINER.W1": 2.0,
            "TRAINER.W2": 4.0,
            "OPTIM.MAX_EPOCH": 2,
            "OPTIM.LR": 0.0026,
        },
        "FGVCAircraft": {
            "TRAINER.KDPT_MAPLE_2.PROMPT_DEPTH": 3,
            "TRAINER.KDPT_MAPLE_2.N_CTX": 2,
            "TRAINER.W": 4.0,
            "TRAINER.W1": 2.0,
            "TRAINER.W2": 4.0,
            "OPTIM.MAX_EPOCH": 2,
            "OPTIM.LR": 0.0026,
        },
        "SUN397": {
            "TRAINER.KDPT_MAPLE_2.PROMPT_DEPTH": 3,
            "TRAINER.KDPT_MAPLE_2.N_CTX": 2,
            "TRAINER.W": 4.0,
            "TRAINER.W1": 2.0,
            "TRAINER.W2": 4.0,
            "OPTIM.MAX_EPOCH": 2,
            "OPTIM.LR": 0.0026,
        },
        "DescribableTextures": {
            "TRAINER.KDPT_MAPLE_2.PROMPT_DEPTH": 3,
            "TRAINER.KDPT_MAPLE_2.N_CTX": 2,
            "TRAINER.W": 4.0,
            "TRAINER.W1": 2.0,
            "TRAINER.W2": 4.0,
            "OPTIM.MAX_EPOCH": 2,
            "OPTIM.LR": 0.0026,
        },
        "EuroSAT": {
            "TRAINER.KDPT_MAPLE_2.PROMPT_DEPTH": 3,
            "TRAINER.KDPT_MAPLE_2.N_CTX": 2,
            "TRAINER.W": 4.0,
            "TRAINER.W1": 2.0,
            "TRAINER.W2": 4.0,
            "OPTIM.MAX_EPOCH": 2,
            "OPTIM.LR": 0.0026,
        },
        "UCF101": {
            "TRAINER.KDPT_MAPLE_2.PROMPT_DEPTH": 3,
            "TRAINER.KDPT_MAPLE_2.N_CTX": 2,
            "TRAINER.W": 4.0,
            "TRAINER.W1": 2.0,
            "TRAINER.W2": 4.0,
            "OPTIM.MAX_EPOCH": 2,
            "OPTIM.LR": 0.0026,
        },
    }.get(dataset, {})

    return " ".join([f"{k} {v}" for k, v in cfg.items()]).split(" ")
